// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google"; // Corrected import name
import "./globals.css";

import Script from 'next/script'; // Import the Script component
// import Clarity from '@microsoft/clarity';

const geistSans = Geist({

  variable: "--font-geist-sans",

  subsets: ["latin"],

});



const geistMono = Geist_Mono({

  variable: "--font-geist-mono",

  subsets: ["latin"],

});





export const metadata = {
  title: "Portfolio | Adit Saxena",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const clarityProjectId = "q3rubtkacg";

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap"
          rel="stylesheet"
        />
        <style>{`
          .material-symbols-outlined {
            font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24;
            vertical-align: middle;
          }
        `}</style>

        <script
          src="https://app.splitx.live/sdk.js"
          data-api-key="sk_live_KNV6xy6iCdTmuTcLD2iRddY54ByYSSgvajJ9-6hv7Hs"
          strategy="afterInteractive"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}


        {/* Add the Clarity script using next/script */}
        <Script id="microsoft-clarity-init" strategy="afterInteractive" defer>
          {`
            (function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "${clarityProjectId}");
          `}
        </Script>
      </body>
    </html>
  );
}