// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google"; // Corrected import name
import "./globals.css";

import Script from 'next/script'; // Import the Script component
// import Clarity from '@microsoft/clarity';

const geistSans = Geist({

  variable: "--font-geist-sans",

  subsets: ["latin"],

});



const geistMono = Geist_Mono({

  variable: "--font-geist-mono",

  subsets: ["latin"],

});





export const metadata = {
  title: "Portfolio | Adit Saxena",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const clarityProjectId = "q3rubtkacg";

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap"
          rel="stylesheet"
        />
        <style>{`
          .material-symbols-outlined {
            font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24;
            vertical-align: middle;
          }
        `}</style>
        <script dangerouslySetInnerHTML={{ __html: `!function(t,e){"use strict";var n=!1;function r(){if(!n){n=!0;var t=e.getElementById("__sx_af");t&&t.parentNode&&t.parentNode.removeChild(t)}}t.__sx_reveal=r,setTimeout(r,2e3);try{var o=localStorage.getItem("sx_changes_v1");if(!o)return;var a=JSON.parse(o),i=Object.keys(a);if(!i.length)return;for(var l="",s="",c=0;c<i.length;c++){var p=a[i[c]];if(p&&p.selector){var f=p.selector;if(l+=f+"{opacity:0!important;transition:none!important}",p.styles){var d="";for(var m in p.styles)Object.prototype.hasOwnProperty.call(p.styles,m)&&(d+=m+":"+p.styles[m]+"!important;");d&&(s+=f+"{"+d+"}")}if(p.text&&p._cs){var v=p._cs;s+=f+"{color:transparent!important;-webkit-text-fill-color:transparent!important;font-size:0!important}"+f+'::before{content:"'+p.text.replace(/\\/g,"\\\\").replace(/"/g,'\\"')+'";color:'+v.color+"!important;-webkit-text-fill-color:"+v.color+"!important;font-size:"+v.fontSize+"!important;font-weight:"+v.fontWeight+";font-family:"+v.fontFamily+";letter-spacing:"+v.letterSpacing+";display:block}"}}}if(!l)return;var y=e.createElement("style");if(y.id="__sx_af",y.textContent=l,(e.head||e.documentElement).appendChild(y),s){var _=e.createElement("style");_.id="__sx_v",_.textContent=s,(e.head||e.documentElement).appendChild(_)}"loading"===e.readyState?e.addEventListener("DOMContentLoaded",r):r()}catch(t){r()}}(window,document);` }} />
        <script
          async
          src="https://app.splitx.live/sdk.js"
          data-api-key="sx_pub_U0_SUI_HVX_hzkqRVrnDacJdyjk7oM5PI1tC6qJOAUM">
        </script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}


        {/* Add the Clarity script using next/script */}
        <Script id="microsoft-clarity-init" strategy="afterInteractive" defer>
          {`
            (function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "${clarityProjectId}");
          `}
        </Script>
      </body>
    </html>
  );
}