// src/app/layout.js
import { Geist, Geist_Mono } from "next/font/google"; // Corrected import name
import "./globals.css";

import Script from 'next/script'; // Import the Script component
// import Clarity from '@microsoft/clarity';

const geistSans = Geist({

  variable: "--font-geist-sans",

  subsets: ["latin"],

});



const geistMono = Geist_Mono({

  variable: "--font-geist-mono",

  subsets: ["latin"],

});





export const metadata = {
  title: "Portfolio | Adit Saxena",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const clarityProjectId = "q3rubtkacg";

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&display=swap"
          rel="stylesheet"
        />
        <style>{`
          .material-symbols-outlined {
            font-variation-settings: 'FILL' 0, 'wght' 400, 'GRAD' 0, 'opsz' 24;
            vertical-align: middle;
          }
        `}</style>
        <script dangerouslySetInnerHTML={{ __html: `!function(t,e){"use strict";var r=!1;function n(){if(!r){r=!0;var t=e.getElementById("__sx_af");t&&t.parentNode&&t.parentNode.removeChild(t)}}t.__sx_reveal=n,t.__sx_applied=!1,setTimeout(n,2e3);try{var o=localStorage.getItem("sx_changes_v1");if(!o)return;var a=JSON.parse(o),i=Object.keys(a);if(!i.length)return;for(var l="",s="",c=0;c<i.length;c++){var p=a[i[c]];if(p)for(var f=p.elements?p.elements:p.selector?[{selector:p.selector,styles:p.styles,text:p.text,_cs:p._cs}]:[],d=0;d<f.length;d++){var m=f[d];if(m&&m.selector){var _=m.selector;if(l+=_+"{opacity:0!important;transition:none!important}",m.styles){var v="";for(var y in m.styles)Object.prototype.hasOwnProperty.call(m.styles,y)&&(v+=y+":"+m.styles[y]+"!important;");v&&(s+=_+"{"+v+"}")}if(m.text&&m._cs){var x=m._cs,h=String.fromCharCode(92);s+=_+"{color:transparent!important;-webkit-text-fill-color:transparent!important;font-size:0!important}"+_+'::before{content:"'+m.text.split(h).join(h+h).split('"').join(h+'"')+'";color:'+x.color+"!important;-webkit-text-fill-color:"+x.color+"!important;font-size:"+x.fontSize+"!important;font-weight:"+x.fontWeight+";font-family:"+x.fontFamily+";letter-spacing:"+x.letterSpacing+";display:block}"}}}}if(!l)return;t.__sx_applied=!0;var g=e.createElement("style");if(g.id="__sx_af",g.textContent=l,(e.head||e.documentElement).appendChild(g),s){var u=e.createElement("style");u.id="__sx_v",u.textContent=s,(e.head||e.documentElement).appendChild(u)}"loading"===e.readyState?e.addEventListener("DOMContentLoaded",n):n()}catch(t){n()}}(window,document);` }} />
        <script
          async
          src="http://localhost:3000/sdk.js?v=4"
          data-api-key="sx_pub_xLtAhZ7cnk-zfzSBBqIj2cHt-S99-qYrTuAghxZnYUg">
        </script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}


        {/* Add the Clarity script using next/script */}
        <Script id="microsoft-clarity-init" strategy="afterInteractive" defer>
          {`
            (function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "${clarityProjectId}");
          `}
        </Script>
      </body>
    </html>
  );
}